Repository dart-frog-dev/dart_frog, pull requests merged in 2022-11, with the labels that each got.

#408 chore(dart_frog_cli): v0.2.3
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#411 fix(dart_frog): Request.json() and Response.json() return types
  examples/todos/routes/todos/[id].dart
  examples/todos/routes/todos/index.dart
  packages/dart_frog/lib/src/request.dart
  packages/dart_frog/lib/src/response.dart
  packages/dart_frog/test/src/request_test.dart
  packages/dart_frog/test/src/response_test.dart
Labels: bug

#414 chore(bricks): upgrade to mason 0.1.0-dev.37
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
Labels: dependencies

#415 fix(dart_frog_cli): hook execution after pub cache clean
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: bug, dependencies

#416 chore(dart_frog_cli): v0.2.4
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#413 docs(routes): fix typos in code snippets
  docs/docs/basics/routes.md
Labels: documentation

#412 chore(dart_frog): v0.3.0
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#418 chore(dart_frog_cli): v0.3.0
  bricks/create_dart_frog/__brick__/pubspec.yaml
  examples/counter/pubspec.yaml
  examples/echo/pubspec.yaml
  examples/hello_world/pubspec.yaml
  examples/kitchen_sink/pubspec.yaml
  examples/todos/pubspec.yaml
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/runtime_compatibility.dart
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
  packages/dart_frog_cli/test/src/runtime_compatibility_test.dart
Labels: chore

#420 chore(bricks): upgrade to mason ^0.1.0-dev.38
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
Labels: chore, dependencies

#421 feat(dart_frog_cli): upgrade to mason ^0.1.0-dev.38
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: enhancement, dependencies

#423 chore(dart_frog_cli): v0.3.1
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#428 feat(dart_frog): add `formData` to Request/Response
  examples/kitchen_sink/e2e/greet_test.dart
  examples/kitchen_sink/e2e/index_test.dart
  examples/kitchen_sink/e2e/pets_test.dart
  examples/kitchen_sink/e2e/users_test.dart
  packages/dart_frog/lib/src/_internal.dart
  packages/dart_frog/lib/src/body_parsers/body_parsers.dart
  packages/dart_frog/lib/src/body_parsers/form_data.dart
  packages/dart_frog/lib/src/request.dart
  packages/dart_frog/lib/src/response.dart
  packages/dart_frog/test/src/body_parsers/form_data_test.dart
  packages/dart_frog/test/src/request_test.dart
  packages/dart_frog/test/src/response_test.dart
Labels: enhancement

#431 test(e2e): add kitchen sink routes and tests for `formData`
  examples/kitchen_sink/e2e/projects_test.dart
  examples/kitchen_sink/routes/projects/index.dart
  examples/kitchen_sink/test/routes/projects/index_test.dart
Labels: e2e

#432 docs(routes): add formData
  docs/docs/basics/routes.md
Labels: documentation

#427 refactor(bricks): decompose hooks into multiple files
  bricks/create_dart_frog/hooks/.gitignore
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/.gitignore
  bricks/dart_frog_dev_server/hooks/pre_gen.dart
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/src/exit_overrides.dart
  bricks/dart_frog_dev_server/hooks/src/report_external_path_dependencies.dart
  bricks/dart_frog_dev_server/hooks/src/report_rogue_routes.dart
  bricks/dart_frog_dev_server/hooks/src/report_route_conflicts.dart
  bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart
  bricks/dart_frog_dev_server/hooks/test/src/exit_overrides_test.dart
  bricks/dart_frog_dev_server/hooks/test/src/report_external_path_dependencies_test.dart
  bricks/dart_frog_dev_server/hooks/test/src/report_rogue_routes_test.dart
  bricks/dart_frog_dev_server/hooks/test/src/report_route_conflicts_test.dart
  bricks/dart_frog_prod_server/hooks/post_gen.dart
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/src/create_bundle.dart
  bricks/dart_frog_prod_server/hooks/src/dart_pub_get.dart
  bricks/dart_frog_prod_server/hooks/src/exit_overrides.dart
  bricks/dart_frog_prod_server/hooks/src/get_path_dependencies.dart
  bricks/dart_frog_prod_server/hooks/src/report_external_path_dependencies.dart
  bricks/dart_frog_prod_server/hooks/src/report_rogue_routes.dart
  bricks/dart_frog_prod_server/hooks/src/report_route_conflicts.dart
  bricks/dart_frog_prod_server/hooks/test/post_gen_test.dart
  bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/create_bundle_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/dart_pub_get_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/exit_overrides_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/get_path_dependencies_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/report_external_path_dependencies_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/report_rogue_routes_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/report_route_conflicts_test.dart
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: refactor

#433 feat(dart_frog_cli): build supports custom Dockerfile
  packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
  packages/dart_frog_cli/lib/src/commands/build/build.dart
  packages/dart_frog_cli/test/src/commands/build/build_test.dart
Labels: enhancement

#434 docs: leading emojis in sidebar
  docs/docs/advanced/custom_entrypoint.md
  docs/docs/advanced/powered_by_header.md
  docs/docs/basics/dependency-injection.md
  docs/docs/basics/middleware.md
  docs/docs/basics/resources.md
  docs/docs/basics/routes.md
  docs/docs/basics/serving-static-files.md
  docs/docs/basics/testing.md
  docs/docs/deploy/aws-app-runner.md
  docs/docs/deploy/digital-ocean-app-platform.md
  docs/docs/deploy/google-cloud-run.md
  docs/docs/tutorials/_category_.json
  docs/docs/tutorials/counter.md
  docs/docs/tutorials/echo.md
  docs/docs/tutorials/hello_world.md
  docs/docs/tutorials/todos.md
Labels: documentation

#435 docs(advanced): custom `Dockerfile`
  .github/workflows/.docker_tests.yaml
  .github/workflows/examples_kitchen_sink.yaml
  docs/docs/advanced/custom_dockerfile.md
  docs/docs/advanced/powered_by_header.md
  docs/docusaurus.config.js
  docs/yarn.lock
  examples/kitchen_sink/Dockerfile
  packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
  packages/dart_frog_cli/lib/src/commands/build/build.dart
  packages/dart_frog_cli/test/src/commands/build/build_test.dart
Labels: documentation

#436 docs: move cspell ignore
  docs/docs/advanced/custom_dockerfile.md
Labels: documentation
