Repository dart-frog-dev/dart_frog, pull requests merged in 2022-07, with the labels that each got.

#138 fix(dart_frog_gen): nested dynamic directory resolution
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/test/src/build_route_configuration_test.dart
  packages/dart_frog_gen/test/src/path_to_route_test.dart
Labels: bug

#137 docs(middleware): fix typo
  docs/docs/basics/middleware.md
Labels: documentation

#139 chore(dart_frog_gen): v0.0.2-dev.4
  packages/dart_frog_gen/CHANGELOG.md
  packages/dart_frog_gen/pubspec.yaml
Labels: chore

#140 fix(dart_frog_cli): upgrade bricks to dart_frog_gen ^0.0.2-dev.4
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
Labels: bug

#141 chore(dart_frog_cli): v0.0.2-dev.8
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#145 fix(dart_frog): Response `json()` return `Object?`
  packages/dart_frog/lib/src/response.dart
  packages/dart_frog/test/src/response_test.dart
Labels: bug

#146 chore(dart_frog): v0.0.1-dev.10
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#148 docs: open graph description and image
  docs/docusaurus.config.js
  docs/src/pages/index.js
  docs/static/img/meta/open-graph.png
Labels: documentation

#156 ci: add dependabot
  .github/dependabot.yaml
Labels: ci

#158 docs: update mobile hero image
  docs/static/img/hero_image_dark_mobile.svg
Labels: documentation

#159 ci: github actions + npm dependabot config
  .github/dependabot.yaml
Labels: ci

#175 docs: update docs site to dartfrog.vgv.dev
  docs/docusaurus.config.js
Labels: bug, documentation

#176 docs: add CNAME
  CNAME
Labels: documentation

#179 docs: add vgv logo to navbar
  docs/docusaurus.config.js
  docs/src/css/custom.css
  docs/static/img/vgv_logo_black.svg
  docs/static/img/vgv_logo_fill.svg
Labels: documentation

#181 docs: cloud run deploy script fixes
  docs/docs/deploy/google-cloud-run.md
Labels: documentation

#183 refactor(dart_frog_cli): remove redundant dart:io import
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
Labels: refactor

#184 feat(dart_frog_cli): avoid logging empty newlines
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
Labels: enhancement

#186 docs: fix blog image aspect ratio
  docs/src/pages/index.js
Labels: documentation

#182 feat(docs): add AWS app runner deployment docs
  docs/docs/deploy/aws-app-runner.md
Labels: documentation

#187 docs: fix edit this page url
  docs/docusaurus.config.js
Labels: documentation

#188 docs: fix GitHub link
  docs/docusaurus.config.js
Labels: documentation

#190 chore(bricks): upgrade to mason ^0.1.0-dev.29
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
Labels: chore

#191 chore(dart_frog_cli): upgrade to mason ^0.1.0-dev.29
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#194 refactor(dart_frog_gen): make buildRouteConfiguration relative to routes
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/test/src/build_route_configuration_test.dart
Labels: refactor

#197 chore(dart_frog_cli): upgrade to mason 0.1.0-dev.30
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#198 feat(dart_frog_gen): include endpoints in RouteConfiguration
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/test/src/build_route_configuration_test.dart
Labels: enhancement

#199 chore(dart_frog_gen): v0.0.2-dev.5
  packages/dart_frog_gen/CHANGELOG.md
  packages/dart_frog_gen/pubspec.yaml
Labels: chore

#200 feat(dart_frog_dev_server): report route conflicts
  .github/workflows/dart_frog_dev_server.yaml
  bricks/dart_frog_dev_server/hooks/.gitignore
  bricks/dart_frog_dev_server/hooks/analysis_options.yaml
  bricks/dart_frog_dev_server/hooks/pre_gen.dart
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart
Labels: enhancement

#205 feat(dart_frog_prod_server): report route conflicts
  .github/workflows/dart_frog_prod_server.yaml
  bricks/dart_frog_prod_server/hooks/.gitignore
  bricks/dart_frog_prod_server/hooks/analysis_options.yaml
  bricks/dart_frog_prod_server/hooks/post_gen.dart
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart
Labels: enhancement

#210 fix(dart_frog_gen): windows relative import syntax
  .github/workflows/dart_frog_gen.yaml
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
Labels: bug

#211 chore(dart_frog_gen): v0.0.2-dev.6
  packages/dart_frog_gen/CHANGELOG.md
  packages/dart_frog_gen/pubspec.yaml
Labels: chore

#209 chore(deps): upgrade to mason ^0.1.0-dev.31
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#212 chore(dart_frog_cli): v0.0.2-dev.9
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#213 docs: update favicon (32x32)
  docs/static/img/favicon.ico
  example/public/favicon.ico
Labels: documentation

#217 fix(dart_frog): Request/Response headers should be Map<String, String>
  packages/dart_frog/lib/src/request.dart
  packages/dart_frog/lib/src/response.dart
  packages/dart_frog/test/src/hot_reload_test.dart
Labels: bug

#219 chore(dart_frog): v0.0.1-dev.11
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#216 docs(deploy): add digital ocean
  docs/docs/deploy/digital-ocean-app-platform.md
Labels: documentation

#220 docs: update homepage video link to Dart Frog playlist
  docs/src/pages/index.js
Labels: documentation

#221 docs(deploy): fixed typo on Digital Ocean page
  docs/docs/deploy/digital-ocean-app-platform.md
Labels: documentation
