Repository dart-frog-dev/dart_frog, pull requests merged in 2022-05, with the labels that each got.

#25 fix(dart_frog_cli): version string
  packages/dart_frog_cli/lib/src/version.dart
Labels: bug

#42 fix(dart_frog_gen)!: use `[...]` instead of `<...>` for dynamic routes
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/test/src/build_route_configuration_test.dart
Labels: bug

#48 fix(dart_frog_gen): windows route generation
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/lib/src/path_to_route.dart
  packages/dart_frog_gen/test/src/path_to_route_test.dart
Labels: bug

#49 fix(bricks): windows prod build use copyPath
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/pubspec.lock
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
Labels: bug

#55 docs(README): add status code, json, and fun facts
  README.md
Labels: documentation

#56 feat(dart_frog): add fromShelfHandler and fromShelfMiddleware adapters
  packages/dart_frog/lib/src/_internal.dart
  packages/dart_frog/lib/src/request_logger.dart
  packages/dart_frog/lib/src/shelf_adapters.dart
  packages/dart_frog/test/src/shelf_adapters_test.dart
Labels: enhancement

#61 feat: change `Response.json` body to type `Object?`
  packages/dart_frog/lib/src/response.dart
Labels: enhancement

#63 ci(dart_frog_gen): use very_good_workflows
  .github/workflows/dart_frog_gen.yaml
Labels: ci
