Repository dart-frog-dev/dart_frog, pull requests merged in 2022-09, with the labels that each got.

#321 docs(routes): add warning about build_runner and using lib
  docs/docs/basics/routes.md
Labels: documentation

#323 docs(routes): expand on request/response APIs
  docs/docs/basics/routes.md
Labels: documentation

#324 fix(dart_frog_cli): avoid generating an empty .dart_frog directory
  packages/dart_frog_cli/e2e/test/dart_frog_build_test.dart
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
Labels: bug

#326 refactor(dart_frog_cli): use packageName
  packages/dart_frog_cli/lib/src/command_runner.dart
Labels: refactor

#327 feat(dart_frog_cli): use new link api from mason_logger
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: enhancement

#328 chore(dart_frog_cli): v0.1.3
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#329 feat(create_dart_frog): upgrade to Dart 2.18 and Very Good Analysis 3.1.0
  bricks/create_dart_frog/__brick__/analysis_options.yaml
  bricks/create_dart_frog/__brick__/pubspec.yaml
Labels: enhancement

#330 feat(dart_frog_cli): upgrade create bundle
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
Labels: enhancement

#331 fix(dart_frog): update Response.json headers to <String, Object>
  packages/dart_frog/lib/src/response.dart
  packages/dart_frog/test/src/response_test.dart
Labels: bug

#332 chore(dart_frog): v0.1.1
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#333 chore(dart_frog_cli): v0.1.4
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#334 docs: use a custom directory for serving static files
  docs/docs/basics/serving-static-files.md
Labels: documentation

#337 feat(dart_frog): add x-powered-by-header to serve
  packages/dart_frog/lib/src/serve.dart
  packages/dart_frog/pubspec.yaml
  packages/dart_frog/test/src/serve_test.dart
Labels: enhancement

#338 chore(dart_frog): v0.1.2
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#339 feat(dart_frog_dev): report external path dependencies
  bricks/dart_frog_dev_server/hooks/pre_gen.dart
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/test/pre_gen_test.dart
Labels: enhancement

#341 feat(dart_frog_prod): detect external path dependencies
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart
Labels: enhancement

#342 feat(dart_frog_cli): report external path dependencies
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
Labels: enhancement

#343 chore(dart_frog_cli): v0.1.5
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#344 docs(advanced): powered by header
  docs/docs/advanced/powered_by_header.md
Labels: documentation

#348 feat(dart_frog_cli): update prompt and command
  packages/dart_frog_cli/README.md
  packages/dart_frog_cli/lib/src/command_runner.dart
  packages/dart_frog_cli/lib/src/commands/update/update.dart
  packages/dart_frog_cli/pubspec.yaml
  packages/dart_frog_cli/test/src/command_runner_test.dart
  packages/dart_frog_cli/test/src/commands/update/update_test.dart
Labels: enhancement

#349 chore(dart_frog_cli): v0.1.6
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore
