Repository dart-frog-dev/dart_frog, pull requests merged in 2022-12, with the labels that each got.

#438 feat(dart_frog_web_socket): add package:dart_frog_web_socket
  .github/workflows/dart_frog_web_socket.yaml
  packages/dart_frog_web_socket/.gitignore
  packages/dart_frog_web_socket/CHANGELOG.md
  packages/dart_frog_web_socket/LICENSE
  packages/dart_frog_web_socket/README.md
  packages/dart_frog_web_socket/analysis_options.yaml
  packages/dart_frog_web_socket/coverage_badge.svg
  packages/dart_frog_web_socket/example/README.md
  packages/dart_frog_web_socket/lib/dart_frog_web_socket.dart
  packages/dart_frog_web_socket/lib/src/web_socket_handler.dart
  packages/dart_frog_web_socket/pubspec.yaml
  packages/dart_frog_web_socket/test/src/web_socket_handler_test.dart
Labels: enhancement

#443 docs: WebSockets
  README.md
  docs/docs/advanced/powered_by_header.md
  docs/docs/advanced/web_socket.md
  docs/docs/overview.md
  docs/docs/roadmap.md
Labels: documentation

#450 docs: add web_socket_counter example
  .github/workflows/examples_web_socket_counter.yaml
  examples/web_socket_counter/.gitignore
  examples/web_socket_counter/README.md
  examples/web_socket_counter/analysis_options.yaml
  examples/web_socket_counter/e2e/ws_test.dart
  examples/web_socket_counter/lib/counter/counter.dart
  examples/web_socket_counter/lib/counter/cubit/counter_cubit.dart
  examples/web_socket_counter/lib/counter/middleware/counter_provider.dart
  examples/web_socket_counter/lib/counter/models/message.dart
  examples/web_socket_counter/pubspec.yaml
  examples/web_socket_counter/pubspec_overrides.yaml
  examples/web_socket_counter/routes/_middleware.dart
  examples/web_socket_counter/routes/ws.dart
  examples/web_socket_counter/test/counter/cubit/counter_cubit_test.dart
  examples/web_socket_counter/test/routes/_middleware_test.dart
  examples/web_socket_counter/test/routes/ws_test.dart
Labels: documentation

#454 docs(web_socket_counter): create tutorial
  docs/docs/tutorials/web_socket_counter.md
Labels: documentation

#457 test(dart_frog_gen): add tests for multiple variables in route file name
  packages/dart_frog_gen/test/src/build_route_configuration_test.dart
Labels: test

#459 docs(web_socket_counter): fix cURL script in tutorial
  docs/docs/tutorials/web_socket_counter.md
Labels: documentation
