Repository dart-frog-dev/dart_frog, pull requests merged in 2022-06, with the labels that each got.

#71 test(dart_frog_cli): add e2e tests
  .github/workflows/dart_frog_cli.yaml
  packages/dart_frog_cli/e2e/pubspec.yaml
  packages/dart_frog_cli/e2e/test/dev_smoke_test.dart
  packages/dart_frog_cli/e2e/test/helpers/dart_frog_create.dart
  packages/dart_frog_cli/e2e/test/helpers/dart_frog_dev.dart
  packages/dart_frog_cli/e2e/test/helpers/helpers.dart
  packages/dart_frog_cli/e2e/test/helpers/kill_dart_frog_server.dart
  packages/dart_frog_cli/e2e/test/helpers/test_server.dart
Labels: e2e

#76 feat(dart_frog): expand router http method support
  packages/dart_frog/lib/src/_internal.dart
  packages/dart_frog/lib/src/http_method.dart
  packages/dart_frog/lib/src/router.dart
  packages/dart_frog/pubspec.yaml
  packages/dart_frog/test/src/router_test.dart
Labels: enhancement

#82 feat(dart_frog_cli): support custom ports via `--port`
  bricks/dart_frog_dev_server/__brick__/server.dart
  bricks/dart_frog_dev_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/__brick__/build/Dockerfile
  packages/dart_frog_cli/lib/src/commands/build/build.dart
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
Labels: enhancement

#84 chore(dart_frog_cli): v0.0.2-dev.5
  README.md
  ROADMAP.md
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#86 docs: update README with more links
  README.md
Labels: documentation

#91 fix(dart_frog_cli): dev server hotreload stability and error reporting
  bricks/dart_frog_dev_server/__brick__/server.dart
  packages/dart_frog/lib/src/hot_reload.dart
  packages/dart_frog/pubspec.yaml
  packages/dart_frog_cli/e2e/test/dart_frog_dev_test.dart
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
Labels: bug

#93 chore(dart_frog_cli): v0.0.2-dev.6
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#77 docs: add example using object in Response.json to README
  README.md
Labels: documentation

#97 feat(dart_frog): toShelfMiddleware/toShelfHandler adapters
  packages/dart_frog/lib/src/shelf_adapters.dart
  packages/dart_frog/test/src/shelf_adapters_test.dart
Labels: enhancement

#95 docs: create documentation site
  .github/workflows/deploy.yaml
  .github/workflows/docs.yaml
  docs/.eslintrc.js
  docs/.gitignore
  docs/.prettierignore
  docs/.prettierrc
  docs/README.md
  docs/babel.config.js
  docs/docs/basics/_category_.json
  docs/docs/basics/congratulations.md
  docs/docs/basics/dependency-injection.md
  docs/docs/basics/middleware.md
  docs/docs/basics/routes.md
  docs/docs/basics/testing.md
  docs/docs/overview.md
  docs/docs/roadmap.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.js
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/static/.nojekyll
  docs/static/img/bolt.svg
  docs/static/img/dart_frog.png
  docs/static/img/favicon.ico
  docs/static/img/heart.svg
  docs/static/img/logo.svg
  docs/static/img/target.svg
  docs/yarn.lock
Labels: documentation

#98 feat(dart_frog): add cascade
  packages/dart_frog/lib/dart_frog.dart
  packages/dart_frog/lib/src/_internal.dart
  packages/dart_frog/lib/src/cascade.dart
  packages/dart_frog/test/src/cascade_test.dart
Labels: enhancement

#102 feat(dart_frog_gen): add serveStaticFiles to RouteConfiguration
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/test/src/build_route_configuration_test.dart
Labels: enhancement

#103 feat(dart_frog): createStaticFileHandler
  packages/dart_frog/lib/dart_frog.dart
  packages/dart_frog/lib/src/create_static_file_handler.dart
  packages/dart_frog/pubspec.yaml
  packages/dart_frog/test/src/create_static_file_handler_test.dart
Labels: enhancement

#107 ci(deploy): add paths to deploy workflow
  .github/workflows/deploy.yaml
Labels: ci

#105 feat(bricks): update dev server to dart_frog_gen 0.0.2-dev.3
  bricks/dart_frog_dev_server/__brick__/server.dart
  bricks/dart_frog_dev_server/hooks/pre_gen.dart
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
Labels: enhancement

#109 chore(dart_frog): v0.0.1-dev.8
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#108 feat(bricks): update prod server to dart_frog_gen 0.0.2-dev.3
  bricks/dart_frog_prod_server/__brick__/build/bin/server.dart
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
Labels: enhancement

#110 feat(dart_frog_cli): static file support
  packages/dart_frog_cli/e2e/test/helpers/kill_dart_frog_server.dart
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
Labels: enhancement

#112 docs: serving static files
  README.md
  ROADMAP.md
  docs/docs/basics/congratulations.md
  docs/docs/basics/serving-static-files.md
  docs/docs/overview.md
  docs/docs/roadmap.md
Labels: documentation

#115 docs(example): simplify /count implementation
  example/routes/count/_middleware.dart
  example/routes/count/index.dart
  example/test/routes/count/_middleware_test.dart
  example/test/routes/count/index_test.dart
Labels: documentation

#116 docs(example): add favicon
  example/public/favicon.ico
Labels: documentation

#119 docs: minor updates to navbar and footer
  docs/docs/basics/resources.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/css/custom.css
Labels: documentation

#120 docs: add link to verygood.ventures in footer
  docs/docusaurus.config.js
Labels: documentation

#122 docs: replace duplicate roadmap link in footer
  docs/docusaurus.config.js
Labels: documentation

#125 docs(README): remove redundant pub badge
  README.md
Labels: documentation

#128 ci: use semantic-pull-request workflow
  .github/workflows/main.yaml
Labels: ci

#127 docs(roadmap): minor typo corrections
  docs/docs/roadmap.md
Labels: documentation
