Repository dart-frog-dev/dart_frog, pull requests merged in 2023-07, with the labels that each got.

#726 feat(vscode): ensure dart_frog_cli is installed when used
  extensions/vscode/README.md
  extensions/vscode/package.json
  extensions/vscode/src/commands/index.ts
  extensions/vscode/src/commands/install-cli.ts
  extensions/vscode/src/extension.ts
  extensions/vscode/src/test/runTest.ts
  extensions/vscode/src/test/suite/commands/install-cli.test.ts
  extensions/vscode/src/test/suite/extension.test.ts
Labels: enhancement

#747 feat(vscode): add CLI version compatibility functions
  extensions/vscode/package-lock.json
  extensions/vscode/package.json
  extensions/vscode/src/test/suite/utils/cli-version.test.ts
  extensions/vscode/src/utils/cli-version.ts
Labels: enhancement

#748 refactor(vscode): defined isDartFrogCliInstalled
  extensions/vscode/src/commands/install-cli.ts
  extensions/vscode/src/test/suite/commands/install-cli.test.ts
  extensions/vscode/src/utils/cli-version.ts
  extensions/vscode/src/utils/utils.ts
Labels: refactor

#754 ci(vscode): add dependabot
  .github/dependabot.yaml
Labels: ci

#752 feat(vscode): ensure CLI version is compatible
  extensions/vscode/src/commands/install-cli.ts
  extensions/vscode/src/commands/update-cli.ts
  extensions/vscode/src/extension.ts
  extensions/vscode/src/test/suite/commands/install-cli.test.ts
  extensions/vscode/src/test/suite/commands/update-cli.test.ts
  extensions/vscode/src/test/suite/extension.test.ts
  extensions/vscode/src/test/suite/index.ts
  extensions/vscode/src/test/suite/utils/cli-version.test.ts
  extensions/vscode/src/utils/cli-version.ts
  extensions/vscode/src/utils/index.ts
Labels: enhancement, javascript

#755 feat(vscode): suggest installing Dart Frog CLI instead of silently installing
  extensions/vscode/src/extension.ts
  extensions/vscode/src/test/suite/extension.test.ts
Labels: enhancement, javascript

#767 feat(vscode): include create command
  extensions/vscode/README.md
  extensions/vscode/package.json
  extensions/vscode/src/commands/create.ts
  extensions/vscode/src/commands/index.ts
  extensions/vscode/src/extension.ts
  extensions/vscode/src/test/suite/commands/create.test.ts
Labels: enhancement, javascript

#761 feat(vscode): defined workspaceContains pubspec.yaml activation event
  extensions/vscode/package.json
  extensions/vscode/src/extension.ts
Labels: enhancement, javascript

#780 refactor(vscode): clear and improve logic for `new` commands
  extensions/vscode/src/commands/new-middleware.ts
  extensions/vscode/src/commands/new-route.ts
  extensions/vscode/src/test/suite/commands/new-middleware.test.ts
  extensions/vscode/src/test/suite/commands/new-route.test.ts
  extensions/vscode/src/test/suite/utils/dart-frog-structure.test.ts
  extensions/vscode/src/utils/dart-frog-structure.ts
  extensions/vscode/src/utils/index.ts
Labels: javascript, refactor

#818 fix(vscode): alter when command menu palette commands show
  extensions/vscode/package.json
Labels: javascript

#782 feat(vscode): new-route prompt asks for entire route path
  extensions/vscode/src/commands/new-middleware.ts
  extensions/vscode/src/commands/new-route.ts
  extensions/vscode/src/test/suite/commands/new-route.test.ts
  extensions/vscode/src/utils/dart-frog-structure.ts
Labels: enhancement, javascript

#819 fix(vscode): dart frog version parsing when update available
  extensions/vscode/src/test/suite/utils/cli-version.test.ts
  extensions/vscode/src/utils/cli-version.ts
Labels: javascript

#784 feat(vscode): show progress indicator on `new` commands
  extensions/vscode/src/commands/new-middleware.ts
  extensions/vscode/src/commands/new-route.ts
  extensions/vscode/src/test/suite/commands/new-middleware.test.ts
  extensions/vscode/src/test/suite/commands/new-route.test.ts
Labels: enhancement, javascript

#817 feat: add verify-only flag to update command
  packages/dart_frog_cli/lib/src/commands/update/update.dart
  packages/dart_frog_cli/test/src/commands/update/update_test.dart
Labels: enhancement

#828 docs(vscode): update README.md
  extensions/vscode/README.md
  extensions/vscode/assets/new-route-middleware-usage.gif
Labels: documentation, vscode
