Repository dart-frog-dev/dart_frog, pull requests merged in 2023-02, with the labels that each got.

#503 feat(dart_frog_cli): add cli completion
  packages/dart_frog_cli/lib/src/command_runner.dart
  packages/dart_frog_cli/pubspec.yaml
  packages/dart_frog_cli/test/src/command_runner_test.dart
  packages/dart_frog_cli/test/src/commands/create/create_test.dart
Labels: enhancement

#504 feat(dart_frog_cli): upgrade to Dart 2.19 and Very Good Analysis 4.0.0
  packages/dart_frog_cli/analysis_options.yaml
  packages/dart_frog_cli/pubspec.yaml
Labels: enhancement

#523 docs(resources): minor copy update to fun fact blurb
  docs/docs/basics/resources.md
Labels: documentation

#529 refactor(dart_frog_prod): update to Dart 2.19 and Very Good Analysis 4.0.0
  .github/workflows/dart_frog_prod_server.yaml
  bricks/dart_frog_prod_server/hooks/analysis_options.yaml
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/test/post_gen_test.dart
Labels: refactor

#534 refactor(dart_frog_gen): upgrade to Dart 2.19 and Very Good Analysis 4.0.0
  packages/dart_frog_gen/analysis_options.yaml
  packages/dart_frog_gen/lib/src/build_route_configuration.dart
  packages/dart_frog_gen/pubspec.yaml
Labels: refactor

#535 refactor(dart_frog): upgrade to Dart 2.19 and Very Good Analysis 4.0.0
  packages/dart_frog/analysis_options.yaml
  packages/dart_frog/lib/dart_frog.dart
  packages/dart_frog/lib/src/hot_reload.dart
  packages/dart_frog/pubspec.yaml
  packages/dart_frog/test/src/router_test.dart
  packages/dart_frog/test/src/serve_test.dart
Labels: refactor

#536 refactor(dart_frog_web_sockets): upgrade to Dart 2.19 and Very Good Analysis 4.0.0
  packages/dart_frog_web_socket/analysis_options.yaml
  packages/dart_frog_web_socket/pubspec.yaml
Labels: refactor

#538 chore(dart_frog_gen): v0.3.1
  packages/dart_frog_gen/CHANGELOG.md
  packages/dart_frog_gen/pubspec.yaml
Labels: chore

#539 chore(dart_frog): v0.3.3
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#540 chore(dart_frog_web_socket): v0.1.0-dev.3
  packages/dart_frog_web_socket/CHANGELOG.md
  packages/dart_frog_web_socket/pubspec.yaml
Labels: chore

#542 feat(dart_frog_cli): upgrade bundles
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
Labels: enhancement

#544 chore(dart_frog_cli): v0.3.3
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#550 docs: update various dependency references
  docs/docs/overview.md
  docs/docs/tutorials/todos.md
Labels: documentation

#556 refactor(dart_frog_cli): remove duplicate `dart:io` import
  packages/dart_frog_cli/lib/src/commands/dev/dev.dart
Labels: refactor
