Repository dart-frog-dev/dart_frog, pull requests merged in 2024-01, with the labels that each got.

#1191 docs: add gen2 to Google Cloud Run deploy
  docs/docs/deploy/google-cloud-run.md
Labels: waiting for response

#1218 docs(dependency injection): Add a section about ordering providers
  docs/docs/basics/dependency-injection.md
Labels: documentation

#1247 refactor(dart_frog_prod_server): reuse buildDirectory
  bricks/dart_frog_prod_server/hooks/lib/src/create_bundle.dart
  bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/test/src/create_bundle_test.dart
  bricks/dart_frog_prod_server/hooks/test/src/create_external_packages_folder_test.dart
Labels: refactor

#1248 refactor(dart_frog_prod_server): removed unused "externalPathDependencies" context variable
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/test/pre_gen_test.dart
Labels: refactor

#1251 refactor(dart_frog_prod_server): clean `createExternalPackagesFolder` logic
  bricks/dart_frog_prod_server/hooks/lib/src/create_external_packages_folder.dart
Labels: refactor

#1250 test(dart_frog_prod_server): remove unnecessary pubspec.yaml setup
  bricks/dart_frog_prod_server/hooks/test/src/create_external_packages_folder_test.dart
Labels: refactor, test

#1252 refactor(dart_frog_prod_server): simplify and document pubspec.lock fixtures
  bricks/dart_frog_prod_server/hooks/test/pubspec_locks.dart
Labels: refactor, test

#1254 chore(dart_frog_cli): 1.2.1
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#1237 docs: update deploy pages's subtitles to make it clear and consistent
  docs/docs/deploy/aws-app-runner.md
  docs/docs/deploy/digital-ocean-app-platform.md
  docs/docs/deploy/globe.md
  docs/docs/deploy/google-cloud-run.md
Labels: documentation

#1273 refactor(dart_frog_prod_server): define internal `PubspecLock`
  bricks/dart_frog_prod_server/hooks/lib/src/pubspec_lock/pubspec_lock.dart
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/test/src/pubspec_lock/pubspec_lock_test.dart
Labels: refactor
