Repository dart-frog-dev/dart_frog, pull requests merged in 2025-08, with the labels that each got.

#1788 docs: minor landing page improvements
  docs/astro.config.mjs
  docs/src/content/docs/blog/future-of-dart-frog.mdx
  docs/src/content/docs/index.mdx
  docs/src/styles/landing.css
Labels: documentation

#1790 docs: minor fixes to copy and snippets
  docs/src/content/docs/basics/dependency-injection.mdx
  docs/src/content/docs/basics/environment.mdx
  docs/src/content/docs/blog/future-of-dart-frog.mdx
Labels: documentation

#1791 chore: update all repository references
  .github/dependabot.yaml
  CONTRIBUTING.md
  README.md
  assets/dart_frog.png
  docs/src/content/docs/advanced/daemon.mdx
  docs/src/content/docs/advanced/debugging.mdx
  docs/src/content/docs/basics/dependency-injection.mdx
  docs/src/content/docs/tutorials/counter.mdx
  docs/src/content/docs/tutorials/todos.mdx
  docs/src/content/docs/tutorials/web-socket-counter.mdx
  extensions/vscode/CHANGELOG.md
  extensions/vscode/CONTRIBUTING.md
  extensions/vscode/README.md
  extensions/vscode/package.json
  extensions/vscode/src/commands/create.ts
  extensions/vscode/src/commands/new-middleware.ts
  extensions/vscode/src/commands/new-route.ts
  extensions/vscode/src/daemon/protocol/protocol.ts
  extensions/vscode/src/test/suite/utils/cli-version.test.ts
  extensions/vscode/src/utils/cli-version.ts
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/README.md
  packages/dart_frog/pubspec.yaml
  packages/dart_frog_auth/CHANGELOG.md
  packages/dart_frog_auth/README.md
  packages/dart_frog_auth/pubspec.yaml
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/CONTRIBUTING.md
  packages/dart_frog_cli/README.md
  packages/dart_frog_cli/e2e/test/daemon/dev_server_domain_test.dart
  packages/dart_frog_cli/lib/src/command_runner.dart
  packages/dart_frog_cli/pubspec.yaml
  packages/dart_frog_cli/test/src/command_runner_test.dart
  packages/dart_frog_gen/CHANGELOG.md
  packages/dart_frog_gen/README.md
  packages/dart_frog_gen/pubspec.yaml
  packages/dart_frog_test/README.md
  packages/dart_frog_test/pubspec.yaml
  packages/dart_frog_web_socket/README.md
  packages/dart_frog_web_socket/pubspec.yaml
  tool/generate_bundles.sh
  tool/release_ready.sh
Labels: chore

#1797 docs: add discord badge
  README.md
  packages/dart_frog/README.md
  packages/dart_frog_auth/README.md
  packages/dart_frog_cli/README.md
  packages/dart_frog_gen/README.md
  packages/dart_frog_test/README.md
  packages/dart_frog_web_socket/README.md
Labels: documentation

#1804 chore(dart_frog_test): v0.1.1
  packages/dart_frog_test/CHANGELOG.md
  packages/dart_frog_test/pubspec.yaml
Labels: chore

#1806 chore: minor fix to update_cli_bundles
  .github/workflows/update_cli_bundles.yaml
Labels: ci, chore

#1808 chore(bricks): bump mason version
  .github/workflows/update_cli_bundles.yaml
  bricks/create_dart_frog/brick.yaml
  bricks/dart_frog_dev_server/brick.yaml
  bricks/dart_frog_new/brick.yaml
  bricks/dart_frog_prod_server/brick.yaml
Labels: chore, dependencies

#1815 ci: group dependabot updates
  .github/dependabot.yaml
Labels: ci

#1821 feat(dart_frog_lint): add `pkg:dart_frog_lint`
  .github/actions/dart_package/action.yaml
  .github/workflows/dart_frog_lint.yaml
  .github/workflows/publish_dart_frog_lint.yaml
  packages/dart_frog_lint/.gitignore
  packages/dart_frog_lint/CHANGELOG.md
  packages/dart_frog_lint/LICENSE
  packages/dart_frog_lint/README.md
  packages/dart_frog_lint/analysis_options.yaml
  packages/dart_frog_lint/assets/logo.png
  packages/dart_frog_lint/coverage_badge.svg
  packages/dart_frog_lint/example/README.md
  packages/dart_frog_lint/lib/dart_frog_lint.dart
  packages/dart_frog_lint/lib/recommended.yaml
  packages/dart_frog_lint/pubspec.yaml
Labels: feature

#1823 docs(vscode): add release docs
  extensions/vscode/CONTRIBUTING.md
Labels: documentation

#1824 chore: add `pubspec_overrides.yaml`
  packages/dart_frog_auth/pubspec_overrides.yaml
  packages/dart_frog_cli/pubspec_overrides.yaml
  packages/dart_frog_test/pubspec_overrides.yaml
  packages/dart_frog_web_socket/pubspec_overrides.yaml
Labels: chore

#1836 chore: adjust dart_frog_test/example to use dart_frog_lint
  packages/dart_frog_test/example/analysis_options.yaml
  packages/dart_frog_test/example/pubspec.yaml
Labels: chore, dependencies

#1838 chore(dart_frog_cli): `dart format`
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/new/templates/dart_frog_new_bundle.dart
  packages/dart_frog_cli/test/src/command_runner_test.dart
  packages/dart_frog_cli/test/src/commands/build/build_test.dart
  packages/dart_frog_cli/test/src/commands/daemon/daemon_test.dart
  packages/dart_frog_cli/test/src/commands/dev/dev_test.dart
  packages/dart_frog_cli/test/src/commands/list/list_test.dart
  packages/dart_frog_cli/test/src/commands/new/new_test.dart
  packages/dart_frog_cli/test/src/commands/update/update_test.dart
  packages/dart_frog_cli/test/src/daemon/connection_test.dart
  packages/dart_frog_cli/test/src/daemon/daemon_server_test.dart
  packages/dart_frog_cli/test/src/daemon/domain/daemon_domain_test.dart
  packages/dart_frog_cli/test/src/daemon/domain/route_configuration_domain_test.dart
  packages/dart_frog_cli/test/src/dev_server_runner/dev_server_runner_test.dart
  packages/dart_frog_cli/test/src/route_configuration_watcher/route_configuration_watcher_test.dart
Labels: chore

#1841 fix(dart_frog_lint): define analysis_options inline
  packages/dart_frog_lint/CHANGELOG.md
  packages/dart_frog_lint/README.md
  packages/dart_frog_lint/lib/recommended.yaml
  packages/dart_frog_lint/pubspec.yaml
Labels: bug

#1842 refactor: standardize project-wide analysis options
  README.md
  analysis_options.yaml
  bricks/create_dart_frog/__brick__/README.md
  bricks/create_dart_frog/hooks/analysis_options.yaml
  bricks/create_dart_frog/hooks/pubspec.yaml
  bricks/dart_frog_dev_server/hooks/analysis_options.yaml
  bricks/dart_frog_dev_server/hooks/pubspec.yaml
  bricks/dart_frog_new/hooks/analysis_options.yaml
  bricks/dart_frog_new/hooks/pubspec.yaml
  bricks/dart_frog_prod_server/hooks/analysis_options.yaml
  bricks/dart_frog_prod_server/hooks/lib/src/exit_overrides.dart
  bricks/dart_frog_prod_server/hooks/post_gen.dart
  bricks/dart_frog_prod_server/hooks/pre_gen.dart
  bricks/dart_frog_prod_server/hooks/pubspec.yaml
  examples/basic_authentication/README.md
  examples/bearer_authentication/README.md
  examples/counter/README.md
  examples/echo/README.md
  examples/hello_world/README.md
  examples/kitchen_sink/README.md
  examples/todos/README.md
  examples/todos/packages/in_memory_todos_data_source/README.md
  packages/dart_frog/README.md
  packages/dart_frog/analysis_options.yaml
  packages/dart_frog/pubspec.yaml
  packages/dart_frog_auth/README.md
  packages/dart_frog_auth/analysis_options.yaml
  packages/dart_frog_auth/pubspec.yaml
  packages/dart_frog_cli/README.md
  packages/dart_frog_cli/analysis_options.yaml
  packages/dart_frog_cli/e2e/analysis_options.yaml
  packages/dart_frog_cli/e2e/pubspec.yaml
  packages/dart_frog_cli/pubspec.yaml
  packages/dart_frog_gen/README.md
  packages/dart_frog_gen/analysis_options.yaml
  packages/dart_frog_gen/pubspec.yaml
  packages/dart_frog_test/README.md
  packages/dart_frog_test/analysis_options.yaml
  packages/dart_frog_test/example/README.md
  packages/dart_frog_test/pubspec.yaml
  packages/dart_frog_web_socket/README.md
  packages/dart_frog_web_socket/analysis_options.yaml
  packages/dart_frog_web_socket/pubspec.yaml
Labels: refactor

#1843 chore(dart_frog): v1.2.3
  packages/dart_frog/CHANGELOG.md
  packages/dart_frog/pubspec.yaml
Labels: chore

#1844 chore(dart_frog_cli): upgrade minimum dart sdk constraint
  packages/dart_frog_cli/pubspec.yaml
Labels: dependencies

#1845 chore(bundles): regenerate bundles
  packages/dart_frog_cli/lib/src/commands/build/templates/dart_frog_prod_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/create/templates/create_dart_frog_bundle.dart
  packages/dart_frog_cli/lib/src/commands/dev/templates/dart_frog_dev_server_bundle.dart
  packages/dart_frog_cli/lib/src/commands/new/templates/dart_frog_new_bundle.dart
Labels: chore

#1846 chore(dart_frog_cli): v1.2.7
  packages/dart_frog_cli/CHANGELOG.md
  packages/dart_frog_cli/lib/src/version.dart
  packages/dart_frog_cli/pubspec.yaml
Labels: chore

#1849 chore(dart_frog): minor `pubspec.yaml` adjustments
  packages/dart_frog/pubspec.yaml
Labels: chore
